chore: Enable direct commits into develop branch

diff --git a/content/Dot.GitHooks/hooks/commit-msg b/content/Dot.GitHooks/hooks/commit-msg
--- a/content/Dot.GitHooks/hooks/commit-msg
+++ b/content/Dot.GitHooks/hooks/commit-msg
@@ -42,7 +42,7 @@ echo "You can't commit directly to master branch"
 exit 1
 fi
 
-if [ "$branch" = "develop" ]; then
-echo "You can't commit directly to develop branch"
-exit 1
-fi
+# if [ "$branch" = "develop" ]; then
+# echo "You can't commit directly to develop branch"
+# exit 1
+# fi
